---
version: '2'

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:6.1.0
        hostname: zookeeper
        container_name: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    broker:
        image: confluentinc/cp-enterprise-kafka:6.1.0
        hostname: broker
        container_name: broker
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_JMX_PORT: 9101
            KAFKA_JMX_HOSTNAME: localhost
            KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081

    schema-registry:
        image: confluentinc/cp-schema-registry:6.1.0
        hostname: schema-registry
        container_name: schema-registry
        depends_on:
            - broker
        ports:
            - "8081:8081"
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:9092'
            SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

    ksqldb-server:
        #        image: confluentinc/ksqldb-server:0.15.0
        image: confluentinc/cp-ksqldb-server:6.1.0
        hostname: ksqldb-server
        container_name: ksqldb-server
        depends_on:
            - broker
            - schema-registry
        ports:
            - "8088:8088"
        environment:
            KSQL_LISTENERS: http://0.0.0.0:8088
            KSQL_BOOTSTRAP_SERVERS: broker:9092
            KSQL_CONFIG_DIR: "/etc/ksql"
            KSQL_HOST_NAME: ksqldb-server
            KSQL_CACHE_MAX_BYTES_BUFFERING: 0
            KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
            KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
            KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"

    ksqldb-cli:
        image: confluentinc/ksqldb-cli:0.15.0
        container_name: ksqldb-cli
        depends_on:
            - broker
            - ksqldb-server
        entrypoint: /bin/sh
        tty: true

    ksqldb-demo:
        image: kidoni.org/ksqldb-demo:0.0.1-SNAPSHOT
        hostname: ksqldb-demo
        container_name: ksqldb-demo
        depends_on:
            - ksqldb-server
        ports:
            - "8888:8888"
        environment:
            SPRING_PROFILES_ACTIVE: "docker"